serverless to 4-7
openshift-labs/learn-katacoda pull request #1121
Opened 2021-05-25 00:58 UTC by ryanj

* Updating the "Intro to Serverless" scenario to openshift-4-7
* Including a fix for #995

2021-05-31 21:19 UTC, btannous requested changes

2021-05-31 21:19 UTC, btannous commented on developing-on-openshift/serverless/01-prepare.md
> +[olm-docs]: https://docs.openshift.com/container-platform/4.7/operators/olm-adding-operators-to-cluster.html
https://docs.openshift.com/container-platform/4.7/operators/olm-adding-operators-to-cluster.html
404 not found. update this url

2021-05-31 21:19 UTC, btannous commented on developing-on-openshift/serverless/01-prepare.md
> +Next, install the Serverless Operator into the `openshift-operators` project.  We choose the update channel of `4.7` to match the OpenShift Container Platform version that we are using.
This is updated now.  the update channel `4.7` would work, but `stable` is recommended by the docs now (and will be less updating later down the road).

https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/serverless/administration-guide#installing-openshift-serverless

2021-05-31 21:19 UTC, btannous commented on developing-on-openshift/serverless/assets/01-prepare/operator-subscription.yaml
> +  channel: "4.7"
```suggestion
  channel: "stable"
```

2021-05-31 21:19 UTC, btannous commented on developing-on-openshift/serverless/01-prepare.md
> +Next, install the Serverless Operator into the `openshift-operators` project.  We choose the update channel of `4.7` to match the OpenShift Container Platform version that we are using.
```suggestion
Next, install the Serverless Operator into the `openshift-operators` project.  We choose the update channel of `stable`.
```

2021-05-31 21:19 UTC, btannous commented on developing-on-openshift/serverless/01-prepare.md
> +[olm-docs]: https://docs.openshift.com/container-platform/4.7/operators/olm-adding-operators-to-cluster.html
```suggestion
[olm-docs]: https://docs.openshift.com/container-platform/4.7/operators/understanding/olm/olm-understanding-olm.html
```

2021-06-01 16:52 UTC, ryanj commented on developing-on-openshift/serverless/01-prepare.md
> +[olm-docs]: https://docs.openshift.com/container-platform/4.7/operators/olm-adding-operators-to-cluster.html
thanks! should be fixed now

2021-06-01 16:53 UTC, ryanj commented on developing-on-openshift/serverless/01-prepare.md
> +Next, install the Serverless Operator into the `openshift-operators` project.  We choose the update channel of `4.7` to match the OpenShift Container Platform version that we are using.
fixed

2021-06-01 16:53 UTC, ryanj commented on developing-on-openshift/serverless/assets/01-prepare/operator-subscription.yaml
> +  channel: "4.7"
got it

2021-06-02 19:23 UTC, cedricclyburn commented
Looks good to me! Will merge and verify from user POV

2021-06-02 19:24 UTC, merged