Transferring Files in and out of Containers: deployment command update
openshift-labs/learn-katacoda pull request #1169
Opened 2021-06-08 19:46 UTC by cedricclyburn

Fix for #1100 references, still need help with #1081 #1072 issues pertaining to a deployment config error if you'd like to take a look at it @ryanj 🙏

2021-06-11 02:18 UTC, ryanj approved these changes
+1 LGTM

2021-06-21 18:40 UTC, jdob requested changes

2021-06-21 18:40 UTC, jdob commented on introduction/transferring-files/02-downloading-files-from-a-container.md
> -``oc rollout status dc/blog``{{execute}}
Don't delete these, change to deployment/blog

2021-06-22 15:41 UTC, davebrownrational commented
@jdob - changing "dc" to "deployment" works as expected, but then the next command fails:

$ oc rollout status deployment/blog
deployment "blog" successfully rolled out
$ oc get pods --selector deploymentconfig=blog
No resources found in myproject namespace.

2021-06-22 17:43 UTC, jdob commented
Yeah, that one will need to change to be deployment instead of deployment config in the selector, good eye. I didn't test this PR, just eyeballed it, so I'm assuming Cedric is gonna run through it live and catch any of the little ones he missed.

2021-06-22 20:28 UTC, davebrownrational commented
Jason,

	Thanks for the help, and quick reply.  I've been stuck on this
scenario, and the "Prometheus and Grafana" scenario for nearly two months,
with no replies.  Could you ask someone to also run through that scenario?
My ticket is: Prometheus deployment fails · Issue #1098 ·
openshift-labs/learn-katacoda (github.com)
  
  
  



Thanks,
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
 Dave (Doc)                                                                     
 Brown                                                                          
                                                                                
 Client                                                                         
 Success                                                                        
 Architect -                                                                    
 AI                                                                             
 Applications                                                                   
                                                                                
 IBM                                                                            
 Technology                                                                     
 Sales, US                                                                      
 Industrial                                                                     
 Market                                                                         
                                                                                
 Phone:       +1-719-337-6560                                                   
                                                                                
 e-mail:      ***@***.***                                             
                                                                                
 IBM                                                                            
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                






From:	Jason Dobies ***@***.***>
To:	openshift-labs/learn-katacoda
            ***@***.***>
Cc:	davebrownrational ***@***.***>, Comment
            ***@***.***>
Date:	06/22/2021 11:43 AM
Subject:	[EXTERNAL] Re: [openshift-labs/learn-katacoda] Transferring
            Files in and out of Containers: deployment command update
            (#1169)



Yeah, that one will need to change to be deployment instead of deployment
config in the selector, good eye. I didn't test this PR, just eyeballed it,
so I'm assuming Cedric is gonna run through it live and catch any of the
little ones he missed. 


Yeah, that one will need to change to be deployment instead of deployment
config in the selector, good eye. I didn't test this PR, just eyeballed it,
so I'm assuming Cedric is gonna run through it live and catch any of the
little ones he missed.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-22 20:36 UTC, cedricclyburn commented
> Yeah, that one will need to change to be deployment instead of deployment config in the selector, good eye. I didn't test this PR, just eyeballed it, so I'm assuming Cedric is gonna run through it live and catch any of the little ones he missed.

Absolutely! Currently running through QA and I'm about to push + merge :)

2021-06-22 21:22 UTC, davebrownrational commented
@cedricclyburn just ran through it again.  the pod() function doesn't seem to work, but I got around that by copy and pasting the pod ID.  Got all the way to step 5, and got stuck again on dc/dummy.  Are you making changes to that area as well?

2021-06-23 14:04 UTC, jdob commented
Yeah, it looks like he hasn't gotten to step 5 yet. I'm going to mark this as a draft because it doesn't address the full scenario.

As for the pod function, however, that surprises me. Are you calling it with the changes:

`pod deployment=blog`

There may be a point later where it calls it with `deploymentconfig` that needs to be fixed, but otherwise, it should continue to work.

2021-06-23 16:52 UTC, davebrownrational commented
Jason,

	Looks like I made some errors in retyping the commands with
"deployment" instead of "deploymentconfig".  I think I've got that all
correct now, since $POD returns the correct pod ID.  But as you can see,
then trying the rsh, it doesn't understand pod.

$ $POD
blog-5dc99d7545-4dqzt$ oc rsh $POD
Error from server (NotFound): pods "pod" not found


	Where pasting in the pod ID works fine:

$ oc rsh blog-5dc99d7545-4dqzt
(app-root)sh-4.2$



  
  
  




Thanks,
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
 Dave (Doc)                                                                     
 Brown                                                                          
                                                                                
 Client                                                                         
 Success                                                                        
 Architect -                                                                    
 AI                                                                             
 Applications                                                                   
                                                                                
 IBM                                                                            
 Technology                                                                     
 Sales, US                                                                      
 Industrial                                                                     
 Market                                                                         
                                                                                
 Phone:       +1-719-337-6560                                                   
                                                                                
 e-mail:      ***@***.***                                             
                                                                                
 IBM                                                                            
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                






From:	Jason Dobies ***@***.***>
To:	openshift-labs/learn-katacoda
            ***@***.***>
Cc:	davebrownrational ***@***.***>, Comment
            ***@***.***>
Date:	06/23/2021 08:04 AM
Subject:	[EXTERNAL] Re: [openshift-labs/learn-katacoda] Transferring
            Files in and out of Containers: deployment command update
            (#1169)



Yeah, it looks like he hasn't gotten to step 5 yet. I'm going to mark this
as a draft because it doesn't address the full scenario. As for the pod
function, however, that surprises me. Are you calling it with the changes:
pod deployment=blog 


Yeah, it looks like he hasn't gotten to step 5 yet. I'm going to mark this
as a draft because it doesn't address the full scenario.


As for the pod function, however, that surprises me. Are you calling it
with the changes:


pod deployment=blog


There may be a point later where it calls it with deploymentconfig that
needs to be fixed, but otherwise, it should continue to work.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-24 14:21 UTC, rravi6121 commented on introduction/transferring-files/02-downloading-files-from-a-container.md
> -``oc rollout status dc/blog``{{execute}}
@jdob  Or if we just add "--as-deployment-config" it would resolve this issue.
Code snippet:

**_oc new-app --as-deployment-config openshiftkatacoda/blog-django-py --name blog_**

2021-06-24 18:35 UTC, cedricclyburn commented
Just added in the fixes for the PVC section and changes to `deployment/blog`, thank you @jdob @davebrownrational and @rravi6121 for your help! Also providing a solution to #478 and #1202 👍

2021-06-24 19:04 UTC, cedricclyburn commented on introduction/transferring-files/02-downloading-files-from-a-container.md
> -``oc rollout status dc/blog``{{execute}}
Thank you @jdob and @rravi6121! Since I'd already changed to `deployment/config on the file I simply made the change for rollout, but I appreciate the suggestion! I also tested adding the extra flag, it allows you to keep `dc/blog` which is convenient!

2021-06-24 22:49 UTC, merged