New Pipelines Update
openshift-labs/learn-katacoda pull request #958
Opened 2020-11-23 16:34 UTC by cedricclyburn

2020-12-01 18:28 UTC, btannous commented
@cedricclyburn is this good to go or still a work in progress? also do you have this on your katacoda so that I can test/validate it works before merging (if so please share the link!)

Thanks!

2020-12-07 03:35 UTC, cedricclyburn commented
@btannous Just made a small tweak to fix an update, should be good to go! [Here's](https://katacoda.com/cclyburn/courses/cicd-application-delivery/pipelines) the link to test.

2020-12-07 16:26 UTC, btannous reviewed
Looks awesome @cedricclyburn ! I will run through this and verify it all works as expected and then can merge in

2020-12-07 16:26 UTC, btannous commented on middleware/pipelines/set-env.sh
> +curl -LO https://github.com/tektoncd/cli/releases/download/v0.14.0/tkn_0.14.0_Linux_x86_64.tar.gz
I'd suggest a quick update using the Openshift built releases of the tools, can find them here: https://mirror.openshift.com/pub/openshift-v4/clients/pipeline/

2020-12-07 17:22 UTC, btannous requested changes

2020-12-07 17:22 UTC, btannous commented on middleware/pipelines/06trigger-pipeline.md
> +    -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api`{{execute}}
This doesn't seem to work any ideas @cedricclyburn ?

2020-12-09 05:05 UTC, cedricclyburn commented
Fixed due to Joel's magic fix!

2020-12-10 02:38 UTC, btannous approved these changes

2020-12-10 02:38 UTC, merged